#!/bin/sh

source ./Configuration

# setup virtual environment - using full path to virtualenv because
# multiple version of python may be installed
/opt/python3.7/bin/python3 -m venv .
source bin/activate

# subsequent installs
pip install -r requirements.txt
